# Generated by Django 2.2.6 on 2020-08-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('url', models.CharField(default='', max_length=120)),
            ],
            options={
                'db_table': 'carousel',
            },
        ),
    ]
